---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: staging

helmCharts:
  - name: podtato-head
    repo: https://podtato-head.github.io/podtato-head-helm/
    version: 0.3.0
    releaseName: staging-podtato
    namespace: podtato-app
    valuesInline:
      replicaCount: 3           # Staging gets 3 replicas