---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: staging

helmCharts:
  - name: podtato-head
    repo: oci://ghcr.io/podtato-head/charts
    version: 0.3.0
    releaseName: staging-podtato
    namespace: podtato-app
    valuesInline:
      replicaCount: 3           # Staging gets 3 replicas