---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: staging

helmCharts:
  - name: podtato-app
    path: ../../base
    releaseName: staging-podtato
    namespace: podtato-app
    valuesInline:           # Override values for STAGING!
      replicaCount: 3       # Staging gets high availability (3 pods)
      environment: staging