---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: development

helmCharts:
  - name: podtato-head          # The official name of the chart
    repo: https://podtato-head.github.io/podtato-head-helm/  # The remote registry URL
    version: 0.3.0              # Pinning the exact version (Best Practice!)
    releaseName: dev-podtato
    namespace: podtato-app
    valuesInline:
      replicaCount: 1